
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftCONCATleftSTARSYMBOL PLUS STAR LPAREN RPARENexpression : expression STARexpression : expression expression %prec CONCATexpression : expression PLUS expressionexpression : LPAREN expression RPARENexpression : SYMBOL'
    
_lr_action_items = {'STAR':([2,3,4,5,7,8,9,],[5,-5,5,-1,5,-4,5,]),'PLUS':([2,3,4,5,7,8,9,],[6,-5,6,-1,-2,-4,6,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,],[1,1,1,-5,1,-1,1,-2,-4,1,]),'RPAREN':([3,4,5,7,8,9,],[-5,8,-1,-2,-4,-3,]),'$end':([2,3,5,7,8,9,],[0,-5,-1,-2,-4,-3,]),'SYMBOL':([0,1,2,3,4,5,6,7,8,9,],[3,3,3,-5,3,-1,3,-2,-4,3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,1,2,4,6,7,9,],[2,4,7,7,9,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression STAR','expression',2,'p_expression_star','REtoAST.py',25),
  ('expression -> expression expression','expression',2,'p_expression_concate','REtoAST.py',32),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','REtoAST.py',40),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_in_parenthesis','REtoAST.py',48),
  ('expression -> SYMBOL','expression',1,'p_expression_symbol','REtoAST.py',53),
]
